// +build !ignore_autogenerated

// Code generated by defaulter-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&HookConfiguration{}, func(obj interface{}) { SetObjectDefaults_HookConfiguration(obj.(*HookConfiguration)) })
	return nil
}

func SetObjectDefaults_HookConfiguration(in *HookConfiguration) {
	SetDefaults_HookConfiguration(in)
	for i := range in.WebHooks {
		a := &in.WebHooks[i]
		SetDefaults_HookConfigurationItem(a)
		for j := range a.Stages {
			b := &a.Stages[j]
			SetDefaults_HookStage(b)
		}
	}
}
